---
title: "Final Project EDA"
output: rmarkdown::latex_document
---


```{r}
# load all necessary libraries
library(mltools)
library(data.table)
library(dplyr)
library(stringr)
library(klaR)
library(gapminder)
library(ggplot2)
library(dendextend)
library(Hmisc)
library(mlbench)
library(caret)
library(factoextra)
library(NbClust)
library(fossil)
library(countrycode)
library(tidyverse)
library(ggrepel)
library(kableExtra)
library(cluster)
library(xtable)
```

```{r}
# read in data, and summarize

## PHASE 1: EXPLORING DATA ##
data <- read.csv('data/immigration_policies/policy_list.csv')
summary(data)

```

```{r}
# making a copy of our data frame
mod_df <- data.frame(data)

# dropping columns that will not affect our data analysis in any way
mod_df <- mod_df[, -c(32:44)]
colSums(is.na(mod_df))[colSums(is.na(mod_df)) != 0]
colSums(is.na(mod_df))[colSums(is.na(mod_df)) == 0]
```

```{r}
# finding NA values
colSums(is.na(data))[colSums(is.na(data)) != 0]

# prints all columns with no NA values
for (i in 1:length(colnames(mod_df))) {
  column = colnames(mod_df)[i]
  if (sum(is.na(mod_df[, column])) == 0) {
    if (!(column %in% c("ID", "COUNTRY_NAME", "ISO2", "ID", "START_DATE", 
                        "END_DATE", "ISO3"))) {
      print(column)
      print(table(mod_df[, column]))
    }
  }
}
```


```{r}
## PHASE 2: CLEANING DATA

# data cleaning for NA values, mostly one-hot encoding, as we find that data is not missing at random

colSums(is.na(mod_df))[colSums(is.na(mod_df)) != 0]

mod_df$VISA_BAN_NONE <- rep(0, nrow(mod_df))
mod_df[is.na(mod_df$VISA_BAN_TYPE), ]$VISA_BAN_NONE <- 1

mod_df$VISA_BAN_ALL <- rep(0, nrow(mod_df))
mod_df[mod_df$VISA_BAN_TYPE == "All" 
       & !is.na(mod_df$VISA_BAN_TYPE), ]$VISA_BAN_ALL <- 1

mod_df$VISA_BAN_SPECIFIC <- rep(0, nrow(mod_df))
mod_df[mod_df$VISA_BAN_TYPE == "specific" 
       & !is.na(mod_df$VISA_BAN_TYPE), ]$VISA_BAN_SPECIFIC <- 1

mod_df$POLICY_TYPE_COMPLETE <- rep(0, nrow(mod_df))
mod_df[mod_df$POLICY_TYPE ==  "COMPLETE"
       & !is.na(mod_df$POLICY_TYPE), ]$POLICY_TYPE_COMPLETE <- 1

mod_df$POLICY_TYPE_PARTIAL <- rep(0, nrow(mod_df))
mod_df[mod_df$POLICY_TYPE ==  "PARTIAL"
       & !is.na(mod_df$POLICY_TYPE), ]$POLICY_TYPE_PARTIAL <- 1

mod_df$POLICY_TYPE_NON <- rep(0, nrow(mod_df))
mod_df[mod_df$POLICY_TYPE ==  "NOPOLICYIMPLEMENTED"
       & !is.na(mod_df$POLICY_TYPE), ]$POLICY_TYPE_NON <- 1

```

```{r}
## HISTORY_BAN_LIST

# for now, will count the number of commas

# helper function to determine the number of countries 
# i.e., number of commas plus one

country_counter <- function(obj) {
  if (is.na(obj)) {
    return(0)
  }
  return ((str_count(obj, ','))[1] + 1)
}

mod_df$HISTORY_BAN_CLEANED <- unlist(lapply(mod_df$HISTORY_BAN_LIST, country_counter))
mod_df$CITIZEN_LIST_CLEANED <- unlist(lapply(mod_df$CITIZEN_LIST, country_counter))
```


```{r}
# data cleaning for non-NA values
colSums(is.na(mod_df))[colSums(is.na(mod_df)) == 0]

## DATES
mod_df$START_DATE_CLEANED <- as.Date(mod_df$START_DATE, tryFormats = "%m_%d_%y")
mod_df$END_DATE_CLEANED <- as.Date(mod_df$END_DATE, tryFormats = "%m_%d_%y")

# making assumption that "NA" end date means the policy is still in place
# na values --> setting them equal to today's date
mod_df[is.na(mod_df$END_DATE_CLEANED), ]$END_DATE_CLEANED <- Sys.Date()

# making (possibly faulty assumption) that the ``negative" policy lengths were never in place
# set these values equal to zero
mod_df$POLICY_LENGTH <- difftime(mod_df$END_DATE_CLEANED, mod_df$START_DATE_CLEANED, units = c("days"))
mod_df[mod_df$POLICY_LENGTH < 0 & !is.na(mod_df$POLICY_LENGTH), ]$POLICY_LENGTH <- 0
# no policy implemented will have start date of none --> need to set this to zero as well
mod_df[mod_df$POLICY_TYPE == "NOPOLICYIMPLEMENTED", ]$POLICY_LENGTH <- 0
mod_df$POLICY_LENGTH <- as.numeric(mod_df$POLICY_LENGTH)

```


```{r}
# standardize all data:
standardize <- function(col) {
  return((col - mean(col)) / sd(col))
}

vars <- c("COUNTRY_NAME", "ISO3", "VISA_BAN_NONE", "VISA_BAN_SPECIFIC", "VISA_BAN_ALL",
          "HISTORY_BAN_CLEANED", "CITIZEN_LIST_CLEANED", "POLICY_LENGTH",
          "POLICY_TYPE_COMPLETE", "POLICY_TYPE_PARTIAL", "AIR", "LAND", "SEA", 
          "POLICY_TYPE_NON", "REFUGEE", "COUNTRY_EXCEP", "WORK_EXCEP")

cleaned_df <- subset(mod_df, select=vars)
ind <- sapply(cleaned_df, is.numeric)
cleaned_df[ind] <- lapply(cleaned_df[ind], standardize)

```



```{r}

by_country <- aggregate(cbind(VISA_BAN_NONE, VISA_BAN_SPECIFIC, VISA_BAN_ALL,
                              HISTORY_BAN_CLEANED,
                              CITIZEN_LIST_CLEANED, POLICY_LENGTH, POLICY_TYPE_NON, 
                              POLICY_TYPE_COMPLETE, POLICY_TYPE_PARTIAL,
                              AIR, LAND, 
                              SEA, REFUGEE, COUNTRY_EXCEP, WORK_EXCEP)~ISO3, data = cleaned_df, mean)

```


```{r}
summary(cleaned_df)
new_vars <- c("VISA_BAN_NONE", "VISA_BAN_SPECIFIC", "VISA_BAN_ALL",
          "HISTORY_BAN_CLEANED", "CITIZEN_LIST_CLEANED", "POLICY_LENGTH",
          "POLICY_TYPE_COMPLETE", "POLICY_TYPE_PARTIAL", "AIR", "LAND", "SEA", 
          "POLICY_TYPE_NON", "REFUGEE", "COUNTRY_EXCEP", "WORK_EXCEP")
```

```{r}
## PHASE 3: SELECTING VARIABLES ##

# report correlation matrix to see if any chosen variables are redundant:

# helper function to export correlation matrix into latex table

flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

data_cor <- rcorr(as.matrix(cleaned_df[, 3:ncol(cleaned_df)]))
flattenCorrMatrix(data_cor$r, data_cor$P)
```


```{r}
set.seed(98)
# load the library
# calculate correlation matrix
ccor <- round(cor(cleaned_df[, 3:ncol(cleaned_df)]), 2)
# summarize the correlation matrix
# find attributes that are highly corrected (ideally >0.75)
upper <- ccor
upper[upper.tri(ccor)]<-""
upper<-as.data.frame(upper)

lower <- ccor
lower[lower.tri(ccor, diag=TRUE)]<-""
lower<-as.data.frame(lower)

print(xtable(upper), type="latex")
```


DETERMINING THE NUMBER OF CLUSTERS:

```{r}
## PHASE 4: TUNING HYPER-PARAMETERS FOR CLUSTERING ##

set.seed(98)
gap_stat <- clusGap(by_country[,2:ncol(by_country)], kmeans, K.max = 10, B = 50)
jpeg(file="gap_k.jpg")
fviz_gap_stat(
  gap_stat,
  linecolor = "steelblue",
  maxSE = list(method = "Tibs2001SEmax", SE.factor = 1)
)
dev.off()

jpeg(file="gap_h.jpg")
gap_stat <- clusGap(by_country[,2:ncol(by_country)], hcut, K.max = 10)
fviz_gap_stat(
  gap_stat,
  linecolor = "steelblue",
  maxSE = list(method = "Tibs2001SEmax", SE.factor = 1)
)
dev.off()
```




```{r}
# DETERMINING THE LINKAGE CRITERIA

dist_mat <- dist(by_country[,2:ncol(by_country)], method = 'euclidean')

# testing different linkage methods

h1=hclust(dist_mat,method='average')
h2=hclust(dist_mat,method='complete')
h3=hclust(dist_mat,method='centroid')
h4=hclust(dist_mat,method='single')
h5=hclust(dist_mat,method="ward.D")
h6=hclust(dist_mat,method="ward.D2")
h7=hclust(dist_mat,method="mcquitty")
h8=hclust(dist_mat,method="median")

# Cophenetic Distances, for each linkage
c1=cophenetic(h1)
c2=cophenetic(h2)
c3=cophenetic(h3)
c4=cophenetic(h4)
c5=cophenetic(h5)
c6=cophenetic(h6)
c7=cophenetic(h7)
c8=cophenetic(h8)

# Correlations
cor(dist_mat,c1) 
cor(dist_mat,c2) 
cor(dist_mat, c3)
cor(dist_mat,c4)
cor(dist_mat,c5)
cor(dist_mat, c6)
cor(dist_mat,c7)
cor(dist_mat,c8)

# average is the best linkage method
```

```{r}
## PHASE 5 (AND FINAL PHASE): CREATING CLUSTERS AND ANALYZING
# kmeans clustering
set.seed(98)

cluster.results.6 <- kmeans(by_country[,2:ncol(by_country)], 6,nstart = 10)

kcluster_by_country = data.frame(by_country)
kcluster_by_country$cluster <- as.factor(cluster.results.6$cluster)
```


```{r}
# hierarchical clustering

dist_mat <- dist(by_country[,2:ncol(by_country)], method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'average')

jpeg(file="cluster_den.jpg")
plot(hclust_avg)
dev.off()

cut_avg6 <- cutree(hclust_avg, k = 6)

hcluster_by_country6 <- mutate(by_country, cluster = cut_avg6)

hcluster_by_country <- data.frame(by_country)

hcluster_by_country$cluster <- as.factor(hcluster_by_country6$cluster)
```

```{r}
# bringing in demographic data; need life expectancy, literacy rate, and fertility rate
gdp <- read.csv('data/demographic/gdp.csv')
population <- read.csv('data/demographic/population.csv')
life_expectancy <- read.csv('data/demographic/life_expectancy.csv')
fertility_rate <- read.csv('data/demographic/fertility_rate.csv')
literacy_rate <- read.csv('data/demographic/literacy_rate.csv')
iso3 <- read.csv('data/demographic/iso3.csv')
```


```{r}
# the world bank had some missing values, which were filled in by hand (since one data source did not have all of the missing values)

gdp[gdp$Code == "ABW", ]$GDP = 3202 * 10^6
gdp[gdp$Code == "AND", ]$GDP = 3155 * 10^6
gdp[gdp$Code == "ERI", ]$GDP = 2.07 * 10^9
gdp[gdp$Code == "GIB", ]$GDP = 2885810912.00
gdp[gdp$Code == "GRL", ]$GDP = 3052 * 10^6
gdp[gdp$Code == "LIE", ]$GDP = 6839 * 10^6
gdp[gdp$Code == "MNP", ]$GDP = 1182 * 10^6
gdp[gdp$Code == "NCL", ]$GDP = 10 * 10^9
gdp[gdp$Code == "PYF", ]$GDP = 3.45 * 10^9
gdp[gdp$Code == "SMR", ]$GDP = 1616 * 10^6 
gdp[gdp$Code == "SSD", ]$GDP = 1119.7 * 10^6 
gdp[gdp$Code == "TKM", ]$GDP = 45231 * 10^6 
gdp[gdp$Code == "VEN", ]$GDP = 47.26 * 10^9
gdp[gdp$Code == "YEM", ]$GDP = 23486 * 10^6

life_expectancy[life_expectancy$Code == "AND", ]$Expectancy = 84.5
life_expectancy[life_expectancy$Code == "ASM", ]$Expectancy = 73.32
life_expectancy[life_expectancy$Code == "CYM", ]$Expectancy = 82.19
life_expectancy[life_expectancy$Code == "DMA", ]$Expectancy = 76.6
life_expectancy[life_expectancy$Code == "GIB", ]$Expectancy = 78.7
life_expectancy[life_expectancy$Code == "KNA", ]$Expectancy = 71.34
life_expectancy[life_expectancy$Code == "MCO", ]$Expectancy = 89.4
life_expectancy[life_expectancy$Code == "MHL", ]$Expectancy = 65.24
life_expectancy[life_expectancy$Code == "MNP", ]$Expectancy = 77.1
life_expectancy[life_expectancy$Code == "PLW", ]$Expectancy = 69.13
life_expectancy[life_expectancy$Code == "SMR", ]$Expectancy = 85.42
life_expectancy[life_expectancy$Code == "TCA", ]$Expectancy = 80.6

fertility_rate[fertility_rate$Code == "AND", ]$Fertility = 1.3
fertility_rate[fertility_rate$Code == "ASM", ]$Fertility = 2.28
fertility_rate[fertility_rate$Code == "CYM", ]$Fertility = 1.83
fertility_rate[fertility_rate$Code == "DMA", ]$Fertility = 1.9
fertility_rate[fertility_rate$Code == "GIB", ]$Fertility = 1.91
fertility_rate[fertility_rate$Code == "KNA", ]$Fertility = 2.1
fertility_rate[fertility_rate$Code == "MCO", ]$Fertility = 1.52
fertility_rate[fertility_rate$Code == "MHL", ]$Fertility = 4.5
fertility_rate[fertility_rate$Code == "MNP", ]$Fertility = 2.66
fertility_rate[fertility_rate$Code == "PLW", ]$Fertility = 2.21
fertility_rate[fertility_rate$Code == "SMR", ]$Fertility = 1.3
fertility_rate[fertility_rate$Code == "TCA", ]$Fertility = 1.7
```


```{r}
# some data cleaning on literacy rates

literacy_rate <- merge(literacy_rate, iso3, by.x = "country", by.y = "Country")
literacy_rate <- subset(literacy_rate, select = c(latestRate, Alpha.3.code))
colnames(literacy_rate) <- c('literacy', 'Code')
literacy_rate$Code <- trimws(literacy_rate$Code)
```


```{r}
# merging all demographic factors
master_df_k <- merge(kcluster_by_country, gdp, by.x = "ISO3", by.y = "Code")
master_df_k <- merge(master_df_k, population, by.x = "ISO3", by.y = "Code")
master_df_k <- merge(master_df_k, life_expectancy, by.x = "ISO3", by.y = "Code")
master_df_k <- merge(master_df_k, fertility_rate, by.x = "ISO3", by.y = "Code")
master_df_k <- merge(master_df_k, literacy_rate, by.x = "ISO3", by.y = "Code")
master_df_k <- subset(master_df_k, select = -c(Name.x, X.x, Name.y, X.y))

master_df_h <- merge(hcluster_by_country, gdp, by.x = "ISO3", by.y = "Code")
master_df_h <- merge(master_df_h, population, by.x = "ISO3", by.y = "Code")
master_df_h <- merge(master_df_h, life_expectancy, by.x = "ISO3", by.y = "Code")
master_df_h <- merge(master_df_h, fertility_rate, by.x = "ISO3", by.y = "Code")
master_df_h <- merge(master_df_h, literacy_rate, by.x = "ISO3", by.y = "Code")
master_df_h <- subset(master_df_h, select = -c(Name.x, X.x, Name.y, X.y))
```



```{r}
# anova 
k_gdp <- aov(GDP ~ cluster, data = master_df_k)
k_pop <- aov(Pop ~ cluster, data = master_df_k) 
k_exp <- aov(Expectancy ~ cluster, data = master_df_k) 
k_fert <- aov(Fertility ~ cluster, data = master_df_k) 
k_lit <- aov(literacy ~ cluster, data = master_df_k) 

summary(k_gdp)
summary(k_pop)
summary(k_exp)
summary(k_fert)
summary(k_lit)
```

```{r}
h_gdp <- aov(GDP ~ cluster, data = master_df_h)
h_pop <- aov(Pop ~ cluster, data = master_df_h) 
h_exp <- aov(Expectancy ~ cluster, data = master_df_h) 
h_fert <- aov(Fertility ~ cluster, data = master_df_h) 
h_lit <- aov(literacy ~ cluster, data = master_df_h) 

summary(h_gdp)
summary(h_pop)
summary(h_exp)
summary(h_fert)
summary(h_lit)
```


```{r}
# merge continent and development level into the data
continents <- read.csv('data/demographic/continent.csv')
continents <- subset(continents, select = c(continent, code_3))
old <- c("Asia", "Europe", "Africa", "Oceania", "Americas")
new <- 1:length(old)
continents$continent[continents$continent %in% old] <- new[match(continents$continent, 
                                                                 old, nomatch = 0)]
continents$continent <- as.numeric(continents$continent)
master_df_k_continent <- merge(master_df_k, continents, by.x = "ISO3", by.y = "code_3")
master_df_h_continent <- merge(master_df_h, continents, by.x = "ISO3", by.y = "code_3")
```


```{r}
# countries into development level by human demographic index, with these cutoffs: https://hdr.undp.org/en/content/human-development-report-2020-readers-guide

hdi <- read.csv('data/demographic/hdi.csv')
hdi <- merge(hdi, iso3, by.x = "country", by.y = "Country")
hdi <- subset(hdi, select = c(hdi, Alpha.3.code))
colnames(hdi) <- c('hdi', 'Code')
hdi$development <- rep(1, nrow(hdi))
hdi[hdi$hdi >= 0.55 & hdi$hdi <= 0.699, ]$development <- 2
hdi[hdi$hdi >= 0.7 & hdi$hdi <= 0.799, ]$development <- 3
hdi[hdi$hdi >= 0.8, ]$development <- 4
hdi$Code <- trimws(hdi$Code)

master_df_k_hdi <- merge(master_df_k, hdi, by.x = "ISO3", by.y = "Code")
master_df_h_hdi <- merge(master_df_h, hdi, by.x = "ISO3", by.y = "Code")

```


```{r}
# compute rand index to compare different clusterings
rand.index(as.numeric(levels(master_df_k_continent$cluster))[master_df_k_continent$cluster],
           master_df_k_continent$continent)
rand.index(as.numeric(levels(master_df_h_continent$cluster))[master_df_h_continent$cluster],
           master_df_k_continent$continent)
rand.index(as.numeric(levels(master_df_h_continent$cluster))[master_df_h_continent$cluster],
           as.numeric(levels(master_df_k_continent$cluster))[master_df_k_continent$cluster])
rand.index(as.numeric(levels(master_df_k_hdi$cluster))[master_df_k_hdi$cluster], 
           master_df_k_hdi$development)
rand.index(as.numeric(levels(master_df_h_hdi$cluster))[master_df_h_hdi$cluster], 
           master_df_h_hdi$development)
```

```{r}
# generating graphs: possible pairs

#       [,1]         [,2]        
#  [1,] "GDP"        "Pop"       
#  [2,] "GDP"        "Expectancy"
#  [3,] "GDP"        "Fertility" 
#  [4,] "GDP"        "literacy"  
#  [5,] "Pop"        "Expectancy"
#  [6,] "Pop"        "Fertility" 
#  [7,] "Pop"        "literacy"  
#  [8,] "Expectancy" "Fertility" 
#  [9,] "Expectancy" "literacy"  
# [10,] "Fertility"  "literacy"  

# plot clusters on different demographic variables, in an attempt to see a pattern

vars <- c("GDP", "Pop", "Expectancy", "Fertility", "literacy")
pairs <- t(combn(vars, 2))

p2 <- ggplot(master_df_k, aes(x = log(GDP), y = log(Pop), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_k, aes(x = log(GDP), y = log(Expectancy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

jpeg("k_twoway.jpeg")
p2 <- ggplot(master_df_k, aes(x = log(GDP), y = log(Fertility), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")
dev.off()

p2 <- ggplot(master_df_k, aes(x = log(GDP), y = log(literacy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_k, aes(x = log(GDP), y = log(Expectancy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_k, aes(x = log(Pop), y = log(Expectancy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_k, aes(x = log(Pop), y = log(Fertility), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_k, aes(x = log(Pop), y = log(literacy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_k, aes(x = log(Expectancy), y = log(Fertility), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_k, aes(x = log(Fertility), y = log(literacy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("K-Means: 6 Clusters") + scale_fill_brewer(palette="Set3")
```

```{r}
p2 <- ggplot(master_df_h, aes(x = log(GDP), y = log(Pop), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_h, aes(x = log(GDP), y = log(Expectancy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_h, aes(x = log(GDP), y = log(Fertility), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_h, aes(x = log(GDP), y = log(literacy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_h, aes(x = log(GDP), y = log(Expectancy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_h, aes(x = log(Pop), y = log(Expectancy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_h, aes(x = log(Pop), y = log(Fertility), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

jpeg('hac_twoway.jpeg')
p2 <- ggplot(master_df_h, aes(x = log(Pop), y = log(literacy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")
dev.off()

p2 <- ggplot(master_df_h, aes(x = log(Expectancy), y = log(Fertility), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")

p2 <- ggplot(master_df_h, aes(x = log(Fertility), y = log(literacy), color = cluster)) +
  geom_point(size=2)
p2 + ggtitle("HAC: 6 Clusters") + scale_fill_brewer(palette="Set3")
```

```{r}
# manually label outliers for boxplots, need variable that indicates whether that country is an outlier for its specific cluster

master_df_k$outlier_expectancy <- rep(0, nrow(master_df_k))
for (i in 1:10) {
  med = median(master_df_k[master_df_k$cluster == i, ]$Expectancy)
  iqr = IQR(master_df_k[master_df_k$cluster == i, ]$Expectancy)
  master_df_k[master_df_k$cluster == i, ]$outlier_expectancy <- 
    (master_df_k[master_df_k$cluster == i, ]$Expectancy> med + 1.5 * iqr) |
    (master_df_k[master_df_k$cluster == i, ]$Expectancy < med - 1.5 * iqr)
}

master_df_k$outlier_gdp <- rep(0, nrow(master_df_k))
for (i in 1:10) {
  med = median(log(master_df_k[master_df_k$cluster == i, ]$GDP))
  iqr = IQR(log(master_df_k[master_df_k$cluster == i, ]$GDP))
  master_df_k[master_df_k$cluster == i, ]$outlier_gdp <- 
    (log(master_df_k[master_df_k$cluster == i, ]$GDP) > med + 1.5 * iqr) |
    (log(master_df_k[master_df_k$cluster == i, ]$GDP) < med - 1.5 * iqr)
}

```


```{r}
# outliers for df_h

master_df_h$outlier_expectancy <- rep(0, nrow(master_df_h))
for (i in 1:10) {
  med = median(master_df_k[master_df_h$cluster == i, ]$Expectancy)
  iqr = IQR(master_df_k[master_df_h$cluster == i, ]$Expectancy)
  master_df_h[master_df_h$cluster == i, ]$outlier_expectancy <- 
    (master_df_h[master_df_h$cluster == i, ]$Expectancy> med + 1.5 * iqr) |
    (master_df_h[master_df_h$cluster == i, ]$Expectancy < med - 1.5 * iqr)
}

master_df_h$outlier_gdp <- rep(0, nrow(master_df_h))
for (i in 1:10) {
  med = median(log(master_df_h[master_df_h$cluster == i, ]$GDP))
  iqr = IQR(log(master_df_h[master_df_h$cluster == i, ]$GDP))
  master_df_h[master_df_h$cluster == i, ]$outlier_gdp <- 
    (log(master_df_h[master_df_h$cluster == i, ]$GDP) > med + 1.5 * iqr) |
    (log(master_df_h[master_df_h$cluster == i, ]$GDP) < med - 1.5 * iqr)
}

# for NON-significant test result

master_df_h$outlier_literacy <- rep(0, nrow(master_df_h))
for (i in 1:10) {
  med = median(master_df_h[master_df_h$cluster == i, ]$literacy)
  iqr = IQR(master_df_h[master_df_h$cluster == i, ]$literacy)
  master_df_h[master_df_h$cluster == i, ]$outlier_literacy <- 
    (master_df_h[master_df_h$cluster == i, ]$literacy > med + 1.5 * iqr) |
    (master_df_h[master_df_h$cluster == i, ]$literacy < med - 1.5 * iqr)
}
```


```{r}
# non-significant test result
jpeg(file="boxplot_h_literacy.jpg")
# do this manually
ggplot(master_df_h, aes(x = cluster, y = literacy, fill = cluster)) +
  geom_boxplot(alpha = 0.3) +
  geom_point(aes(color = cluster, group = cluster), position = position_dodge(width=0.75)) +
  geom_text_repel(aes(group = cluster, 
                label = ifelse(outlier_literacy, 
                  yes = ISO3,
                  no = '')), 
            position = position_dodge(width=0.75),
            hjust = "left", size = 3) + 
  ggtitle("Country Literacy by HAC Cluster") + xlab("Policy Cluster") + theme(legend.position = "none")
dev.off()
```


```{r}
jpeg(file="boxplot_h_gdp.jpg")
ggplot(master_df_h[!is.na(master_df_h$GDP), ], aes(x = cluster, y = log(GDP), fill = 
                                                     cluster)) +
  geom_boxplot(alpha = 0.3) +
  geom_point(aes(color = cluster, group = cluster), position = position_dodge(width=0.75)) +
  geom_text_repel(aes(group = cluster, 
                label = ifelse(outlier_gdp, 
                  yes = ISO3,
                  no = '')), 
            position = position_dodge(width=0.75),
            hjust = "left", size = 3) +
  ggtitle("Country GDP by HAC Cluster") + xlab("Policy Cluster") + theme(legend.position = "none")
dev.off()
```

```{r}
jpeg(file="boxplot_k_gdp.jpg")
ggplot(master_df_k, aes(x = cluster, y = log(GDP), fill = 
                                                     cluster)) +
  geom_boxplot(alpha = 0.3) +
  geom_point(aes(color = cluster, group = cluster), position = position_dodge(width=0.75)) +
  geom_text_repel(aes(group = cluster, 
                label = ifelse(outlier_gdp, 
                  yes = ISO3,
                  no = '')), 
            position = position_dodge(width=0.75),
            hjust = "left", size = 3) +
  ggtitle("Country GDP by K-Means Cluster") + xlab("Policy Cluster") + theme(legend.position = "none")
dev.off()
```


```{r}
jpeg(file = "boxplot_k_expectancy.jpg")
ggplot(master_df_k, 
       aes(x = cluster, y = Expectancy, fill = cluster)) +
  geom_boxplot(alpha = 0.3) +
  geom_point(aes(color = cluster, group = cluster), position = position_dodge(width=0.75)) +
  geom_text_repel(aes(group = cluster, 
                label = ifelse(outlier_expectancy, 
                  yes = ISO3,
                  no = '')), 
            position = position_dodge(width=0.75),
            hjust = "left", size = 3) + ggtitle("Country Life Expectancy by K-Means Cluster") + 
  xlab("Policy Cluster") + theme(legend.position = "none")
dev.off()
```
```{r}
## BOXPLOT QUESTIONS
jpeg(file = "boxplot_h_expectancy.jpg")
ggplot(master_df_h, 
       aes(x = cluster, y = Expectancy, fill = cluster)) +
  geom_boxplot(alpha = 0.3) +
  geom_point(aes(color = cluster, group = cluster), position = position_dodge(width=0.75)) +
  geom_text_repel(aes(group = cluster, 
                label = ifelse(outlier_expectancy, 
                  yes = ISO3,
                  no = '')), 
            position = position_dodge(width=0.75),
            hjust = "left", size = 3) + ggtitle("Country Life Expectancy by HAC Cluster") + xlab("Policy Cluster") + 
  theme(legend.position = "none")
dev.off()
```


```{r}
# extracting names of each country
iso3$Alpha.3.code <- trimws(iso3$Alpha.3.code)
names_h <- merge(master_df_h, iso3, by.x = "ISO3", by.y = "Alpha.3.code")
names_k <- merge(master_df_k, iso3, by.x = "ISO3", by.y = "Alpha.3.code")
```

```{r}
# unfortunately could not find a better way to export countries into a table -- printing out the names of countries in each cluster

for (i in 1:6) {
  print(names_h[names_h$cluster == i, ]$Country)
}
```


```{r}
# unfortunately could not find a better way to export countries into a table -- printing out the names of countries in each cluster

for (i in 1:6) {
  print(names_k[names_k$cluster == i, ]$Country)
}
```


```{r}
# reporting demographic means for each cluster, in latex format
demographic_means <- aggregate(cbind(GDP, Pop, Expectancy, Fertility, literacy)~cluster, 
                               data = master_df_k, mean)
demographic_means <- lapply(demographic_means, function(x) if(is.numeric(x)) round(x, 3) else x)
demographic_means <- data.frame(demographic_means)
names(demographic_means)[names(demographic_means) == 'cluster'] <- 'cluster'
kable(demographic_means, "latex")

demographic_means <- aggregate(cbind(GDP, Pop, Expectancy, Fertility, literacy)~cluster, 
                               data = master_df_h, mean)
demographic_means <- lapply(demographic_means, function(x) if(is.numeric(x)) round(x, 3) else x)
demographic_means <- data.frame(demographic_means)
names(demographic_means)[names(demographic_means) == 'cluster'] <- 'cluster'
xtable(demographic_means, "latex")
```

```{r}
# reporting policy means for each cluster, in latex format
cluster_means <- aggregate(cbind(VISA_BAN_NONE, VISA_BAN_SPECIFIC, VISA_BAN_ALL,
                HISTORY_BAN_CLEANED,
                CITIZEN_LIST_CLEANED, POLICY_LENGTH, POLICY_TYPE_NON, 
                POLICY_TYPE_COMPLETE, POLICY_TYPE_PARTIAL,
                AIR, LAND, 
                SEA, REFUGEE, COUNTRY_EXCEP, WORK_EXCEP)~cluster, data = master_df_h, mean)
cluster_means <- lapply(cluster_means, function(x) if(is.numeric(x)) round(x, 3) else x)
cluster_means <- data.frame(cluster_means)
names(cluster_means)[names(cluster_means) == 'cluster'] <- 'cluster'
xtable(cluster_means[,1:5], format = "latex")
xtable(cluster_means[,c(1,6:9)], format = "latex")
xtable(cluster_means[,c(1,10:13)], format = "latex")
xtable(cluster_means[,c(1,14:15)], format = "latex")
```


```{r}
cluster_means <- aggregate(cbind(VISA_BAN_NONE, VISA_BAN_SPECIFIC, VISA_BAN_ALL,
                HISTORY_BAN_CLEANED,
                CITIZEN_LIST_CLEANED, POLICY_LENGTH, POLICY_TYPE_NON, 
                POLICY_TYPE_COMPLETE, POLICY_TYPE_PARTIAL,
                AIR, LAND, 
                SEA, REFUGEE, COUNTRY_EXCEP, WORK_EXCEP)~cluster, data = master_df_k, mean)
cluster_means <- lapply(cluster_means, function(x) if(is.numeric(x)) round(x, 3) else x)
cluster_means <- data.frame(cluster_means)
names(cluster_means)[names(cluster_means) == 'cluster'] <- 'cluster'
xtable(cluster_means[,1:5], format = "latex")
xtable(cluster_means[,c(1,6:9)], format = "latex")
xtable(cluster_means[,c(1,10:13)], format = "latex")
xtable(cluster_means[,c(1,14:15)], format = "latex")
```


```{r}
# clusters on first two principal components, to justify structures of each cluster
library(ggfortify)
policy.pca <- prcomp(master_df_h[,2:ncol(by_country)], center = TRUE,scale. = TRUE)
# summary(policy.pca)
jpeg(file="pca_hac.jpg")
g <- autoplot(policy.pca, data = master_df_h, colour = 'cluster')
g + ggtitle('HAC Clustering on First Two Principal Components') + labs(colour = 'cluster')
dev.off()
```

```{r}
policy.pca <- prcomp(master_df_k[,2:ncol(by_country)], center = TRUE,scale. = TRUE)
# summary(policy.pca)
jpeg(file="pca_k.jpg")
g <- autoplot(policy.pca, data = master_df_k, colour = 'cluster')
g + ggtitle('K-Means Clustering on First Two Principal Components') + labs(colour = 'cluster')
dev.off()
```

